dataset:
  image_folder: dataset/clothing-dataset/images
  csv_path: dataset/clothing-dataset/images.csv
  label_mapping:
    Blazer: 0
    Blouse: 1
    Body: 2
    Dress: 3
    Hat: 4
    Hoodie: 5
    Longsleeve: 6
    Not sure: 7
    Other: 8
    Outwear: 9
    Pants: 10
    Polo: 11
    Shirt: 12
    Shoes: 13
    Shorts: 14
    Skip: 15
    Skirt: 16
    T-Shirt: 17
    Top: 18
    Undershirt: 19

logs:
  checkpoint_folder: checkpoints

training:
  folds:
    train:
      - 0
      - 1
      - 2
    val:
      - 3
    test:
      - 4
  use_wandb: true
  device: cuda:0
  epochs: 1000
  use_image_caching: true
  batch_size: 96
  dataloader_num_workers: 6
  

model:
  __class_fullname__: source.models.TimmSimSiam
  backbone_name: resnet50d
  timm_pretrained: false
  projection_dim: 2048
  prediction_dim: 512

criterion:
  __class_fullname__: source.losses.NegativeCosineSimilarity
  dim: 1

optimizer:
  __class_fullname__: torch.optim.SGD
  lr: 0.5
  weight_decay: 0.0001
  momentum: 0.9

scheduler:
  __class_fullname__: torch.optim.lr_scheduler.CosineAnnealingLR

augmentations:
  train:
    transform:
      __class_fullname__: Compose
      transforms:
        - __class_fullname__: albumentations.augmentations.crops.transforms.RandomResizedCrop
          height: 224
          width: 224
          scale:
            - 0.2
            - 1.0
          always_apply: true
        - __class_fullname__: albumentations.augmentations.transforms.ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.1
          p: 0.8
        - __class_fullname__: albumentations.augmentations.transforms.ToGray
          p: 0.2
        - __class_fullname__: albumentations.augmentations.transforms.GaussianBlur
          sigma_limit:
            - 0.1
            - 2.0
          p: 0.5
        - __class_fullname__: albumentations.augmentations.geometric.transforms.HorizontalFlip
          p: 0.5

        # To PyTorch tensors.
        - __class_fullname__: albumentations.augmentations.transforms.Normalize
          always_apply: true
        - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2
          always_apply: true
  val:
    transform:
      __class_fullname__: Compose
      transforms:
        - __class_fullname__: albumentations.augmentations.geometric.resize.Resize
          height: 224
          width: 224
        # To PyTorch tensors.
        - __class_fullname__: albumentations.augmentations.transforms.Normalize
          always_apply: true
        - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2
          always_apply: true
  test:
    transform:
      __class_fullname__: Compose
      transforms:
        - __class_fullname__: albumentations.augmentations.geometric.resize.Resize
          height: 224
          width: 224
        # To PyTorch tensors.
        - __class_fullname__: albumentations.augmentations.transforms.Normalize
          always_apply: true
        - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2
          always_apply: true